-- Tours Seeder for JamJam Trek
-- 6 Popular Nepal Tour Packages
-- Run this SQL in your database to seed tour data

INSERT INTO tours (
    title,
    destination,
    description,
    price,
    currency,
    discount_price,
    duration_days,
    duration_nights,
    difficulty_level,
    max_group_size,
    min_group_size,
    tour_type,
    available_slots,
    is_featured,
    is_popular,
    is_active,
    created_at,
    updated_at
) VALUES
(
    'Kathmandu Valley Cultural Tour',
    'Kathmandu',
    'Explore the rich cultural heritage of Kathmandu Valley with visits to UNESCO World Heritage Sites including Pashupatinath Temple, Boudhanath Stupa, Swayambhunath (Monkey Temple), and Kathmandu Durbar Square. Experience the vibrant culture, ancient architecture, and spiritual atmosphere of Nepal''s capital city.',
    299,
    'USD',
    249,
    3,
    2,
    'Easy',
    15,
    2,
    'cultural',
    12,
    1,
    1,
    1,
    NOW(),
    NOW()
),
(
    'Pokhara Adventure Package',
    'Pokhara',
    'Discover the natural beauty of Pokhara, the adventure capital of Nepal. Enjoy paragliding over Phewa Lake, visit the World Peace Pagoda, explore mysterious caves, witness stunning sunrise views from Sarangkot, and experience the serene lakeside atmosphere. Perfect blend of adventure and relaxation.',
    450,
    'USD',
    399,
    4,
    3,
    'Easy',
    12,
    2,
    'adventure',
    10,
    1,
    1,
    1,
    NOW(),
    NOW()
),
(
    'Chitwan Jungle Safari',
    'Chitwan National Park',
    'Experience the wilderness of Chitwan National Park, a UNESCO World Heritage Site. Enjoy elephant safari, jungle walks, canoe rides on Rapti River, bird watching, and cultural performances by Tharu community. Spot one-horned rhinoceros, Bengal tigers, and diverse wildlife in their natural habitat.',
    380,
    'USD',
    350,
    3,
    2,
    'Easy',
    10,
    2,
    'wildlife',
    8,
    1,
    1,
    1,
    NOW(),
    NOW()
),
(
    'Lumbini Pilgrimage Tour',
    'Lumbini',
    'Visit Lumbini, the birthplace of Lord Buddha and a UNESCO World Heritage Site. Explore the sacred Maya Devi Temple, Ashoka Pillar, monasteries from different countries, and the peaceful Lumbini Garden. A spiritual journey through Buddhist history and culture.',
    320,
    'USD',
    NULL,
    2,
    1,
    'Easy',
    15,
    1,
    'pilgrimage',
    15,
    0,
    0,
    1,
    NOW(),
    NOW()
),
(
    'Nepal Heritage Circuit',
    'Kathmandu, Pokhara, Chitwan',
    'Comprehensive tour covering Nepal''s top three destinations. Start in Kathmandu with cultural sightseeing, continue to Pokhara for mountain views and adventure activities, and end in Chitwan for jungle safari. Experience the perfect combination of culture, nature, and wildlife in one amazing journey.',
    899,
    'USD',
    799,
    8,
    7,
    'Moderate',
    12,
    4,
    'cultural',
    6,
    1,
    1,
    1,
    NOW(),
    NOW()
),
(
    'Upper Mustang Jeep Tour',
    'Upper Mustang',
    'Embark on an extraordinary journey to the forbidden kingdom of Upper Mustang. Drive through dramatic landscapes, ancient monasteries, cave dwellings, and the walled city of Lo Manthang. Experience Tibetan Buddhist culture, stunning desert-like terrain, and breathtaking Himalayan views. A unique adventure to one of Nepal''s most remote regions.',
    1299,
    'USD',
    1199,
    10,
    9,
    'Moderate',
    8,
    2,
    'adventure',
    5,
    1,
    1,
    1,
    NOW(),
    NOW()
);

-- Note: Images need to be added manually through the admin panel
-- The seeder creates tours without featured images or gallery images
